### PR TITLE
Wait for the image to be correctly created

### LINKED ISSUE #274: Saving an image randomly fails on AWS
As originally reported by @NanoMarc 

=== Version ===
- 2.0.0

=== Steps to reproduce ===
- Setup a Nanocloud 2.0.0 on AWS
- Publish some app
- Wait one hour
- Open a VDI and try to save an image

=== Expected Result ===
- A new image is saved and an AMI is created

=== Actual Result ===
- It seems an error occur but the AMI has been created

=== Analysis ===
- If you try a second time to save the image, it works (a message says "OK" and an AMI is created)
- The problem seems not related to the timeout on AWS for the AMI creation
- Several customers have seen this issue

### PR DESCRIPTION
**Pull request by corentindrouet**
Fixes #274

### CODE REVIEW

File: api/controllers/ImageController.js [hunk 1]
```diff
@@ -72,6 +72,13 @@ module.exports = {
       return res.badRequest('Invalid base machine ID');
     }
 
+    /**
+     * Sometimes aws can take several minutes to create an image,
+     * but the default timeout is 120 secondes (2 minutes).
+     * Upping it to 600 secondes (10 minutes, it's arbitrary) permit
+     * to be sur that aws have the time to create an image.
```
Comment (Gentux) [inline api/controllers/ImageController.js]: sur => sure
