### PR TITLE
Regular user can use storage correctly in VDI with an image created by the admin

### LINKED ISSUE #172: When a VM is created from an image, personal storage for users is broken
This bug has been seen in the following conditions.
- Release nanocloud 2.0.0beta3 (may be it is also the case in previous versions)
- IaaS is AWS
- Dev or Production mode (same result)

Process:
- Install an application and publish it (onboard it)
- Create then an image from this current VM (button "Save an image")
- Disconnect VDI

This image will then be automatically used for the next VMs. When a normal user connects, he has the published application but the personal storage is then broken (Z:). This issue does not affect the administrator.

Workaround (as a regular user):
- disconnect Z:
- disconnect VDI
- reconnect VDI (Desktop)

### PR DESCRIPTION
**Pull request by Leblantoine**
Fixes #172 
When an image is created the storage configuration is saved for admin, when a regular user want to use this image the storage was corrupted, user can't access to his storage.

If we have a storage in `z:` now we delete it and recreate it. The storage is not corrupted anymore.

### CODE REVIEW

File: api/controllers/AppController.js [hunk 1]
```diff
@@ -140,8 +140,41 @@ module.exports = {
                   })
                     .catch(() => {
                       // User storage is probably already mounted
+                      // When an image is published, sometimes storage does not work again
+                      // Let's delete the currupted storage and recreate it
                       // Let's ignore the error silently
-                      return Promise.resolve();
+
+                      console.log('1');
```
Comment (dynamiccast) [inline api/controllers/AppController.js]: Remaining `console.log`.

**Review by dynamiccast — CHANGES_REQUESTED** [review]

**Review by dynamiccast — APPROVED** [review]
