### PR TITLE
Regular users cannot see group they are in from their profile page

### LINKED ISSUE #87: Regular users cannot see group they are in from their profile page
Steps to reproduce:

Create a group
Create a regular user
Add user into the group
Log in a regular user
Go to profile page

The _group_ section says `no groups`

### PR DESCRIPTION
**Pull request by spacewoox**
This problem occurs when we attempt to retrieve a single user. The backend does not populate the 'groups' property. To fix that, I ensure the relationships are correctly sent.
Additionally, there was an indent issue in the template file that has been fixed.

Fixes #87

### CODE REVIEW

**Comment by dynamiccast** [comment]
It works if you  refresh the user's profile page.
But if you follow the following workflow it does not:
- login as a regular user
- go straight to profile

This is because `/api/users?me=true` does not return any associations. This can be updated by addding `pospulate('groups')` in the query in `config/passport.js:121`.

File: api/controllers/UserController.js [hunk 1]
```diff
@@ -29,6 +29,13 @@
 
 module.exports = {
 
+  findOne: function(req, res) {
+    return User.findOne(req.allParams().id)
+    .populate('groups')
+    .then((res.ok))
```
Comment (dynamiccast) [inline api/controllers/UserController.js:35]: Extra parenthesis
