### PR TITLE
Catch errors when fetching sessions informations

### LINKED ISSUE #247: Errors when fetching sessions information should be catch
Sessions statuses are polled on every Windows in the database. When a Windows is booting or being shut down, the request fails and the error is never caught.

The following error appears in the log:

```
backend_1           | 0|app      | Unhandled rejection Error: connect ETIMEDOUT 52.57.56.182:9090
backend_1           | 0|app      |     at Object.exports._errnoException (util.js:1008:11)
backend_1           | 0|app      |     at exports._exceptionWithHostPort (util.js:1031:20)
backend_1           | 0|app      |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
backend_1           | 0|app      | Unhandled rejection Error: connect ETIMEDOUT 52.57.56.182:9090
backend_1           | 0|app      |     at Object.exports._errnoException (util.js:1008:11)
backend_1           | 0|app      |     at exports._exceptionWithHostPort (util.js:1031:20)
backend_1           | 0|app      |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

```

### PR DESCRIPTION
**Pull request by corentindrouet**
Fixes #247 

If a machine is booting or being shut-down, it will not respond in time, so we catch silently the error.

### CODE REVIEW

File: api/models/Machine.js [hunk 1]
```diff
@@ -131,7 +132,10 @@ module.exports = {
           });
 
           return sessions;
-        });
+        })
+      // If timeout is exceeded, machine is probably booting or being shut-down
+      // Let's ignore the error silently
```
Comment (Gentux) [inline api/models/Machine.js]: Could you indent these comment with the code ?
