### PR TITLE
Machine count down now don't start from the begging when page is refreshed

### LINKED ISSUE #234: Machines expiring count down always start from the begging when page is refreshed
Step to reproduce:
- Connect to the VDI to get assign a machine
- Close the session
- Go back to the machine list
- The count down should start at `sessionDuration`

However, refreshing the page makes the count down starts from the beginning even though no connection to the VDI was made.

It seems to me like a frontend issue since the broker keeps track of the machine inactivity just fine and never looses the count.

### PR DESCRIPTION
**Pull request by corentindrouet**
Fixes #234 .

This bug is due to the fact that the variable 'expiration' is calculated only once.

This bug is resolved by recalculated the expiration variable when it's necessary.

### CODE REVIEW

File: assets/app/protected/machines/index/controller.js [hunk 1]
```diff
@@ -50,11 +50,18 @@ export default Ember.Controller.extend({
   setData: function() {
     var ret = Ember.A([]);
     this.get('items').forEach(function(item) {
+      let now = new Date();
+      let time = window.moment(item.get('endDate'));
+      let res = Math.floor(window.moment.duration(window.moment(time,'DD/MM/YYYY HH:mm:ss').diff(window.moment(now,'DD/MM/YYYY HH:mm:ss')), 'milliseconds').asSeconds());
```
Comment (dynamiccast) [inline assets/app/protected/machines/index/controller.js]: Please avoid calling variable `res`.
