### PR TITLE
Check upload limit before uploading a file.

### LINKED ISSUE #55: Upload quota should be checked before data is actually sent
Step to reproduce:
- Set the upload limit to 10
- Upload a 4GB file

Limit reached messaged is only displayed after the file has actually been uploaded.

### PR DESCRIPTION
**Pull request by Leblantoine**
Fixes #55 
`storageSize` use now the `du` command and return the size of the user storage in KB.
The storageSize is returned in the response of `api/files` in meta in KB.
Unit test is updated and check if storageSize take files in directories into account.

Now the upload limit is checked in front before the file is uploaded. If you are over the limit the error message is immediately display and upload endpoint is not called.
`uploadLimit` is available from configuration service.

### CODE REVIEW

File: api/services/StorageService.js [hunk 1]
```diff
@@ -126,26 +128,30 @@ module.exports = {
...
-      .then((files) => {
-        return new Promise(function(resolve) {
-          for (let i = 0; i < files.data.length; i++) {
-            if (files.data[i].attributes.type === 'directory') {
-              sum += this.storageSize(storage, files.data[i].attributes.name + '/' + dir, 0);
-            } else {
-              sum += files.data[i].attributes.size;
-            }
+  storageSize: function(storage) {
+    return new Promise((resolve, reject) => {
```
Comment (willrnch) [inline api/services/StorageService.js]: useless

File: api/services/StorageService.js [hunk 2]
```diff
@@ -126,26 +128,30 @@ module.exports = {
...
+          if (res.success === false) {
+            return reject(res.stderr);
+          } else {
+            return resolve(res.stdout.split('\t')[0]);
           }
-          return resolve(sum);
-        });
-      });
+        })
+        .catch((err) => reject(err));
```
Comment (willrnch) [inline api/services/StorageService.js]: useless

File: assets/app/components/vdi-drag-n-drop/component.js [hunk 3]
```diff
@@ -137,19 +139,43 @@ export default Ember.Component.extend({
...
     for (let i = 0; i < files.length; i++) {
-      let f = FileUploader.create({
-        file: files[i],
-        token: this.get('session.access_token')
-      });
-      f.one('completed', this, this.completeNotif);
-      f.one('forbidden', this, this.limitNotif);
-      f.one('canceled', this, this.abortNotif);
-      q.pushObject(f);
+      tab.push(files[i]);
```
Comment (willrnch) [inline assets/app/components/vdi-drag-n-drop/component.js]: useless

File: assets/app/components/vdi-drag-n-drop/component.js [hunk 4]
```diff
@@ -137,19 +139,43 @@ export default Ember.Component.extend({
...
     }
+
+    tab.forEach((file) => {
+      this.checkUploadLimit(file.size)
+        .then((res) => {
+          if (res === true) {
```
Comment (willrnch) [inline assets/app/components/vdi-drag-n-drop/component.js]: replace by `if (res) {`
