### PR TITLE
Fix manual driver destroys machine

### LINKED ISSUE #144: No machine should ever be destroyed using manual driver
Currently, machines are removed from database even if manual driver is used.

### PR DESCRIPTION
**Pull request by dynamiccast**
Fixes #144

Check if `destroyMachine` is implemented before trying to remove machine.
Remove `machine.user` when session is over after `sessionDuration`.
Modify `config/env/development` to add `plazaPort` in manual driver example.

### CODE REVIEW

File: config/env/development.js [hunk 1]
```diff
@@ -80,7 +80,8 @@ module.exports = {
      *   type: "manual",
      *   ip: "0.0.0.0"
      *   username: "Administrator",
```
Comment (Gentux) [inline config/env/development.js]: These lines should be single quoted (even if this is a comment)

File: config/env/development.js [hunk 2]
```diff
@@ -80,7 +80,8 @@ module.exports = {
...
-     *   password: "secret"
+     *   password: "secret",
+     *   plazaPort: 9090
```
Comment (Gentux) [inline config/env/development.js]: For unknown reason, setting "plazaPort" raise the following error : 
backend | error: column machine.plazaPort does not exist

Replace by "plazaport" to avoid that
